#wget https://files.grouplens.org/datasets/movielens/ml-1m.zip
#iunzip ml-1m.zip
name: test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install build dependencies
      run: |
        python -p pip install -U setuptools pip
        python -m pip install -r requirements.txt
    - name: PyTest
      run: python -m pip install pytest
    - name: Assets
      run: |
        wget https://files.grouplens.org/datasets/movielens/ml-1m.zip
        unzip ml-1m.zip
    - name: Test
      run: pytest
